# Generated by Django 6.0.5 on 2026-05-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanjob',
            name='level',
            field=models.PositiveSmallIntegerField(default=1, help_text='Attack level (-l). 1=normal, 2=aggressive. Higher = slower.'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='max_attack_time',
            field=models.PositiveIntegerField(default=60, help_text='Max attack time per module in seconds. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='max_links',
            field=models.PositiveSmallIntegerField(default=20, help_text='Max links crawled per page. Lower = faster.'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='max_scan_time',
            field=models.PositiveIntegerField(default=180, help_text='Max total scan time in seconds. 0 = unlimited.'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='scan_depth',
            field=models.PositiveSmallIntegerField(default=2, help_text='Crawl depth (-d). Lower = faster. Recommended: 1-3.'),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='scope',
            field=models.CharField(choices=[('url', 'URL only'), ('page', 'Page'), ('folder', 'Folder (recommended)'), ('subdomain', 'Subdomain'), ('domain', 'Full Domain (slow)')], default='folder', help_text="Crawl scope. 'folder' is the best balance of speed vs coverage.", max_length=20),
        ),
        migrations.AddField(
            model_name='scanjob',
            name='tasks',
            field=models.PositiveSmallIntegerField(default=8, help_text='Parallel async tasks wapiti uses internally (--tasks).'),
        ),
    ]
